### ISSUE TITLE
Line Printer Issue 

### ISSUE THREAD

**Issue by mhmoud100** [FatihGeylan/printer_controller_pr3#1]
com.honeywell.mobility.print.LinePrinterException: Print Service is not available
it gives me This Error and I have Line Print Service Installed

**Comment by FatihGeylan** [comment]
Can you please provide me with more information? 
- Which devices are you working with?
- From which method do you get this error?

**Comment by mhmoud100** [comment]
Sure,
I have an Android 13 Phone (Xiaomi Note 10 5G)
This is the Method that Gives me the error **PrinterTask** 
in this Line lp = LinePrinter(
          jsonCmdAttribStr,
          PrinterID,
          blPrinterUri,
          exSettings
        )
and honeywellintermecpr3 Package is Working For me but the code is too old and I want to run your package

**Comment by FatihGeylan** [comment]
Did you configure your "deviceName" and "deviceId" variables to truly match your printer device? And of course, you should implement all the setup steps mentioned in the important notes part.

**Comment by mhmoud100** [comment]
Yes, I configured the deviceName and my deviceAddress variables and i am running your provided example and didn't work and i dont know why. 
Is there any permissions i have to put to make it work ?

**Comment by FatihGeylan** [comment]
Sorry, I was in compulsory military service therefore I couldn't reply. Could you make it work?

**Comment by mhmoud100** [comment]
no, I just used the service in Honeywell Phone to print on the Honeywell printer and it worked perfectly. it just makes the user take an extra step but it's okay I guess.
And I hope you finish your Military service Well

**Comment by FatihGeylan** [comment]
I'm glad you found a way. Thanks a lot!
